import 'package:family_money_manager/features/foundation_detail/foundation_detail_screen.dart';
import 'package:family_money_manager/features/smoke_screen/smoke_screen.dart';
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

part 'routes.g.dart';

/// Typed route hierarchy for the application.
///
/// All navigable destinations are expressed as [GoRouteData] subclasses.
/// Navigation calls use the typed route object and compile-time verified
/// `location` and `.go(context)` extension methods generated by
/// `go_router_builder`.
///
/// Phase 1.5 defines two routes only:
///   - [SmokeRouteData]          — the application entry point (`/`)
///   - [FoundationDetailRouteData] — proves typed-parameter generation
///
/// Do not add financial feature routes here. They are added in later phases
/// as their screens are implemented.
@TypedGoRoute<SmokeRouteData>(
  path: '/',
  routes: <TypedRoute<GoRouteData>>[
    TypedGoRoute<FoundationDetailRouteData>(path: 'detail/:probeId'),
  ],
)
@immutable
class SmokeRouteData extends GoRouteData with $SmokeRouteData {
  const SmokeRouteData();

  @override
  Widget build(BuildContext context, GoRouterState state) => const SmokeScreen();
}

/// Typed route with a single non-financial string parameter.
///
/// Demonstrates that GoRouter parameter serialization and parsing are
/// compile-time typed. The [probeId] parameter is a simple alphanumeric
/// identifier with no financial meaning.
@immutable
class FoundationDetailRouteData extends GoRouteData with $FoundationDetailRouteData {
  const FoundationDetailRouteData({required this.probeId});

  final String probeId;

  @override
  Widget build(BuildContext context, GoRouterState state) =>
      FoundationDetailScreen(probeId: probeId);
}
