include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/core/localization/app_localizations*.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore

linter:
  rules:
    - always_use_package_imports
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unawaited_futures
    - use_enums
